[[post]]
category = "Courses"
title = "Udemy Certificates"
subtitle = "Over 15 certificates earned. Includes topics for Excel, VBA, SAP, Quality Management, Supply Chain Management and Industry 4.0"
datetime = "2023"
image = "./config/assets/posts/blog-1.jpg"
url = "https://drive.google.com/drive/folders/1IdCMxVkMWaI9MMaDtndOuFlFGj8PR4z8?usp=drive_link"

[[post]]
category = "Volunteer Work"
title = "Experts Exchange"
subtitle = "Over 15 certificates earned. Includes topics for VBA ,C#, JavaScript, Exchange, Azure, PowerShell and Web Development"
datetime = "2019 to 2023"
image = "./config/assets/posts/blog-1.jpg"
url = "https://drive.google.com/drive/folders/1JafV_cCvAdqvu89eWCjcthIQeBsBeAVh?usp=sharing"
