[[doing]]
title = "\n Data Analysis & Modeling"
icon = "./config/assets/icons/DataAnalysis.png"


[[doing]]
title = "\n Automation & Scripting"
icon = "./config/assets/icons/AutomationScripting.png"

[[doing]]
title = "\n Web Development"
icon = "./config/assets/icons/WebDevelopment.png"

[[doing]]
title = "\n Process Optimization"
icon = "./config/assets/icons/ProcessOptimization.png"

[[doing]]
title = "\n Software & API"
icon = "./config/assets/icons/SoftwareAPI.png"
