[[doing]]
title = "\nData Analysis & Modeling"
icon = "./config/assets/icons/DataAnalysis.png"


[[doing]]
title = "\nAutomation & Scripting"
icon = "./config/assets/icons/AutomationScripting.png"

[[doing]]
title = "\nWeb Development"
icon = "./config/assets/icons/WebDevelopment.png"

[[doing]]
title = "\nProcess Optimization"
icon = "./config/assets/icons/ProcessOptimization.png"

[[doing]]
title = "\nSoftware & API"
icon = "./config/assets/icons/SoftwareAPI.png"
