[[doing]]
title = "\n\n Data Analysis & Modeling"
icon = "./config/assets/icons/DataAnalysis.png"


[[doing]]
title = "\n\n Automation & Scripting"
icon = "./config/assets/icons/AutomationScripting.png"

[[doing]]
title = "\n\n Web Development"
icon = "./config/assets/icons/WebDevelopment.png"

[[doing]]
title = "\n\n Process Optimization"
icon = "./config/assets/icons/ProcessOptimization.png"

[[doing]]
title = "\n\n Software & API"
icon = "./config/assets/icons/SoftwareAPI.png"
