[[project]]
title = "Academic Awards"
category = "Awards & Testimonials"
image = "./config/assets/projects/awards.jpg"
url = "https://drive.google.com/drive/folders/1pCDfs-Pzc30kWDXU_EA7zswG5MTN4lQD?usp=sharing"

[[project]]
title = "Testimonial from TSH Group Pte Ltd"
category = "Awards & Testimonials"
image = "./config/assets/projects/tsh.png"
url = "https://drive.google.com/file/d/1e1WNxBT9Z_pJosoFVZ5_pZXUO2MJ-MXp/view?usp=sharing"

[[project]]
title = "Testimonial from Experts Exchange"
category = "Awards & Testimonials"
image = "./config/assets/projects/expertsexchange.png"
url = "https://drive.google.com/file/d/1s2oO2EFdzmUFzzb1JZuzcFmmhVqAsflQ/view?usp=sharing"

[[project]]
title = "Testimonial from Epson Singapore Pte Ltd"
category = "Awards & Testimonials"
image = "./config/assets/projects/epson.png"
url = "https://drive.google.com/file/d/18qfuGxKRcbjC3CN8hwKeckagqtAgf6iB/view?usp=sharing"

[[project]]
title = "Backorder Trend Forecasting"
category = "3D Supply Chain Solutions"
image = "./config/assets/projects/backorder.png"
url = "https://github.com/GoodbyeKittyy/Backorder-Trend-Forecasting"

[[project]]
title = "Order to Delivery KPI Simulation"
category = "3D Supply Chain Solutions"
image = "./config/assets/projects/kpi.png"
url = "https://github.com/GoodbyeKittyy/Order-Creation-to-Delivery-KPI-Simulation"

[[project]]
title = "Processor Gantt Chart"
category = "3D Supply Chain Solutions"
image = "./config/assets/projects/gantt.png"
url = "https://github.com/GoodbyeKittyy/Processor-Gantt-Chart"

[[project]]
title = "Pallet Mole FIFO System" 
category = "3D Supply Chain Solutions"
image = "./config/assets/projects/palletmole.png"
url = "https://github.com/GoodbyeKittyy/Scalable-Pallet-Mole-FIFO-System"

[[project]]
title = "Warehouse Container Optimization"
category = "3D Supply Chain Solutions"
image = "./config/assets/projects/container.png"
url = "https://github.com/GoodbyeKittyy/Advanced-Warehouse-Container-Fulfillment-Optimizer"

[[project]]
title = "Elevator Shuttle Rack System"
category = "3D Supply Chain Solutions"
image = "./config/assets/projects/elevator.png"
url = "https://github.com/GoodbyeKittyy/Shuttle-Rack-System-With-Elevator"

[[project]]
title = "Vertical Conveyor"
category = "3D Blueprints & Architecture"
image = "./config/assets/projects/verticalconveyor.jpg"
url = "https://github.com/GoodbyeKittyy/3D-Vertical-Conveyor-Design"

[[project]]
title = "Warehouse"
category = "3D Blueprints & Architecture"
image = "./config/assets/projects/warehouse.jpg"
url = "https://github.com/GoodbyeKittyy/3D-Warehouse-Design"

[[project]]
title = "Office"
category = "3D Blueprints & Architecture"
image = "./config/assets/projects/office.jpg"
url = "https://github.com/GoodbyeKittyy/3D-Office-Design"

[[project]]
title = "Clinic"
category = "3D Blueprints & Architecture"
image = "./config/assets/projects/clinic.jpg"
url = "https://github.com/GoodbyeKittyy/3D-Clinic-Design"

[[project]]
title = "Order Management"
category = "Databases"
image = "./config/assets/projects/order.png"
url = "https://github.com/GoodbyeKittyy/SQL-Integrated-Order-Management-System"

[[project]]
title = "Invoice Blling Management"
category = "Databases"
image = "./config/assets/projects/billing.png"
url = "https://github.com/GoodbyeKittyy/Time-and-Billing-Management-Database"

[[project]]
title = "Accounts Ledger Management"
category = "Databases"
image = "./config/assets/projects/ledger.png"
url = "https://github.com/GoodbyeKittyy/Accounts-Ledger-Database"

[[project]]
title = "Loan Amortization Management"
category = "Databases"
image = "./config/assets/projects/amortization.png"
url = "https://github.com/GoodbyeKittyy/Loan-Amortization-Database"

[[project]]
title = "Personnel Leave Management"
category = "Databases"
image = "./config/assets/projects/staffleave.png"
url = "https://github.com/GoodbyeKittyy/SQL-Integrated-Staff-Leave-Database"

[[project]]
title = "Membership History Management"
category = "Databases"
image = "./config/assets/projects/membership.png"
url = "https://github.com/GoodbyeKittyy/Membership-Event-History-Database"
