############## Experience config ################
#################################################

[[experience]]
title = "Digital Supply Chain Analyst & Researcher"
timeline = "2024"
company = "Republic Polytechnic"
description = "Support consultancy projects, research and develop new digital solutions for companies, innovate digital tools for industry projects and commercialization."

[[experience]]
title = "Supply Chain Management & Quality Management Professional"
timeline = "2023"
company = "TAK Products & Services Pte Ltd"
description = "Ensure vendor compliance with quality standards, manage ISO certification processes, coordinate audits, conduct Quality Management reviews for returns, and compile Quality Management statistics."

[[experience]]
title = "Demand Forecaster & Supply Chain Management Professional"
timeline = "2019"
company = "EPSON Singapore Pte Ltd"
description = "Develop demand forecasts at multiple levels of aggregation, implement statistical forecast models, preparing budgets & cost analysis, and plan & teach SAP & VBA lessons for staff."

[[experience]]
title = "Hardware Quality Assurance Auditor"
timeline = "2018"
company = "Pactera Singapore Pte Ltd"
description = "Run tests & debugging tools to analyse the functionality of hardware systems, documenting defects & run output simulations, present quality audit reports"


############## Education config #################
#################################################
[[education]]
title = "High school of art and design"
timeline = "2002 — 2004"
description = "Duis aute irure dolor in reprehenderit in voluptate, quila voluptas mag odit aut fugit, sed consequuntur magni dolores eos."

[[education]]
title = "New york academy of art"
timeline = "2006 — 2007"
description = "Ratione voluptatem sequi nesciunt, facere quisquams facere menda ossimus, omnis voluptas assumenda est omnis.."

[[education]]
title = "University school of the arts"
timeline = "2007 — 2008"
description = "Nemo enims ipsam voluptatem, blanditiis praesentium voluptum delenit atque corrupti, quos dolores et quas molestias exceptur."




############## Skills config ####################
#################################################
[skills] 
title = "My Skills"
enabled = true
show_bar = true
show_value = true

[[skill]]
title = "Programming & Automation"
value = "90%"

[[skill]]
title = "Software & API"
value = "70%"

[[skill]]
title = "Web Development"
value = "50%"

[[skill]]
title = "ERP Systems"
value = "80%"

[[skill]]
title = "Supply Chain Management, Research & Analysis"
value = "680%"

############## Language config ##################
#################################################
[languages]
title = "Languages"
enabled = true
show_bar = true
show_value = true

[[language]]
title = "English"
value = "80%"

[[language]]
title = "Chinese"
value = "50%"
