############### Section config ##################
#################################################
title = "Tech Experience"
enabled = true # false

############### Technologies ####################
#################################################
# Technology I have worked with
# name = "./.../../icon_path"
[technologies]
VBA = "./config/assets/icons/vba.svg"
Python = "./config/assets/icons/python.svg"
Java = "./config/assets/icons/java.svg"
C = "./config/assets/icons/c.svg"
"C++" = "./config/assets/icons/cplusplus.svg"
"C#" = "./config/assets/icons/csharp.svg"
HTML = "./config/assets/icons/html.svg"
JavaScript = "./config/assets/icons/javascript.svg"
PHP = "./config/assets/icons/php.svg"
SAP = "./config/assets/icons/sap.svg"
Oracle = "./config/assets/icons/oracle.svg"
"SAGE 300" = { src = "./config/assets/icons/sage300.svg", width = 150, height = 150 }
FlexSim = "./config/assets/icons/flexsim.svg"
"WorkFusion RPAqwa" = "./config/assets/icons/workfusion.svg"
"Microsoft SQL Server" = "./config/assets/icons/microsoftsqlserver.svg"
Excel = "./config/assets/icons/microsoftexcel.svg"
Access = "./config/assets/icons/microsoftaccess.svg"
Exchange = "./config/assets/icons/microsoftexchange.svg"
Project = "./config/assets/icons/microsoftproject.svg"
Visio = "./config/assets/icons/microsoftvisio.svg"
Azure = "./config/assets/icons/microsoftazure.svg"
"Power BI" = "./config/assets/icons/powerbi.svg"
Git = "./config/assets/icons/git.svg"
Figma = "./config/assets/icons/figma.svg"
PowerShell = "./config/assets/icons/powershell.svg"
Linux = "./config/assets/icons/linux.svg"
